### ISSUE TITLE
"ng generate universal server" Angular-CLI command is not working

### ISSUE THREAD

**Issue by rahiakela** [TrainingByPackt/Beginning-Server-Side-Application-Development-with-Angular#1]
Hi,

I am following this book and everything is working fine but I am stuck on the stage where needed "ng generate universal server" Angular-CLI command execution that give the below error:

`PS D:\myworks\angular-projects\angular-social> ng generate universal server
Schematic input does not validate against the Schema: {"appId":"serverApp","main":"main.server.ts","tsconfigFileName":"tsconfig.server","testTsconfigFileName":"tsconfig.spec","appDir":"app","rootModuleFileName":"app.server.module.ts","rootModuleClassName":"AppServerModule","skipInstall":false}
Errors:

  Data path "" should have required property 'clientProject'.
PS D:\myworks\angular-projects\angular-social>`

Please let me know, what is the problem here.

**Comment by lukasgeppert** [comment]
The command you need to run is:
ng g universal --client-project "angular-social"
